image: node:9.11.1

pages:
  cache:
    paths:
    - node_modules/

  script:
  - yarn install
  - yarn run build

  artifacts:
    paths:
    - dist
  
  only:
  - master

pages:
  stage: deploy
  script:
    - mkdir public
    - mv dist/* public
  artifacts:
    paths:
      - public
  only:
    - master
